version: '3.8'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: tasty-tabs
    volumes:
      # These will run on first startup to set up the schema and data.
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql
      - ./dml.sql:/docker-entrypoint-initdb.d/dml.sql
    ports:
      - "5433:5432"

  app:
    build: .
    restart: unless-stopped
    ports:
      - "5002:5002"
    depends_on:
      - db